name: dart_playground
environment:
  sdk: '^3.1.2'
dependencies:
  collection: any
  intl: any
  riverpod: any
  riverpod_annotation: any
dev_dependencies:
  build_runner: any
  lints: any
  riverpod_generator: any
  test: any
