name: dart_playground
environment:
  sdk: '^3.1.2'
dependencies:
  collection: any
  intl: any
  riverpod: any
  riverpod_annotation: any
dev_dependencies:
  build_runner: any
  build_web_compilers: any # https://github.com/dart-lang/build/blob/master/docs/getting_started.md#using-build_runner-as-a-development-server
  lints: any
  riverpod_generator: any
  test: any
