name: dart_playground
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '^3.2.0'
dependencies:
  collection: any
  encrypt: any
  freezed_annotation: any
  intl: any
  json_annotation: any
  logging: any
  riverpod: any
  riverpod_annotation: any
dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  lints: any
  riverpod_generator: any
  test: any
