name: dart_playground
environment:
  sdk: '^3.1.3'
dependencies:
  collection: ^1.18.0
  encrypt: ^5.0.3
  freezed: ^2.4.5
  intl: ^0.18.1
  riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.6 # https://github.com/dart-lang/build/blob/master/docs/getting_started.md#using-build_runner-as-a-development-server
  lints: ^2.1.1
  riverpod_generator: ^2.3.3
  test: ^1.24.8
