on:
  push:
    branches:
      - main
      - develop

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: dart format --output none --set-exit-if-changed .
      - run: dart analyze
      - run: dart test
